site_name: Autonóm robotok és járművek programozása
site_description: 'Research Center of Vehicle Industry'
site_author: 'jkk-research'
site_url: 'https://jkk-research.github.io' # Uncomment to set a canonical URL
copyright: |
  &copy; Author
docs_dir: docs/
repo_url: https://github.com/jkk-research/
nav:
  - index.md
  - Tananyag:
    - 1. Bevezetés: 
      - bevezetes/README.md
      - bevezetes/practice.md
      - bevezetes/gepterem.md
      - GitHub Copilot: bevezetes/copilot.md
      - ROS 1 alapfogalmak: bevezetes/ros1.md
      - Linux, git: bevezetes/linux.md
      - VS code, git: bevezetes/vscode.md
    - 2. Telepítés: 
      - bevezetes/ros2.md
      - bevezetes/ros2gyak.md
      - telepites/ros_humble.md
    - 3. Érzékelés: 
      - erzekeles/README.md
      - erzekeles/practice.md
    - 4. Féléves: 
      - workshops/index.md
      - F1/10 hands-on (ROS 2): workshops/f1tenth_real_a.md
      - ROS 2 install: workshops/ros2_a.md
      - F1/10 simulation (ROS 2): workshops/f1tenth_sim_a.md
      - Wheeltec hands-on (ROS 1) : workshops/wheeltec_real_a.md
    - 5. Transzformációk: 
      - transformations/index.md
      - Transformation
    - 6. Észlelés: 
      - detection/index.md
      - Detection
    - 7. Szimuláció:
      - simulation/index.md
      - Simulation
    - 8. Tervezés:
      - plan/index.md
      - Plan
    - 9. Szabályozás:
      - control/index.md
      - Control
    - 10. AI:
      - ai/index.md
      - AI
  - Nagy féléves, kis beadandó:
    - feleves_beadando/README.md
    - feleves_beadando/kisbeadando.md
    - feleves_beadando/nagyfeleves.md
  - Önálló:
    - onallo/README.md
    - onallo/linux.md
theme:
  logo: /img/jkk03.svg
  name: 'material'
  favicon: '/img/favicon.ico'
  palette:
    - scheme: youtube
      primary: 'custom'
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: black
      # primary: 'custom'
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
  - content.code.copy
  - content.code.select
  # - navigation.expand      # Expand all collapsable sections.
  #- navigation.instant     # Instant loading pages.
  # - navigation.indexes     # Attach pages directly to Sections. Incompatible with "toc.integrate"
  #- navigation.sections    # Render top sections as groups.
  - navigation.tabs         # Render top sections as tabs at the top.
  #- navigation.tabs.sticky # Tabs won't disappear when scrolling down. Requires "navigation.tabs".
  - navigation.top         # Adds a "Back to top" that is shown when scrolling up.
  #- navigation.tracking    # Updates the url with highlighted section anchor.
  
  # Search
  #
  #- search.highlight # Search will highlight the searched word(s) on the page.*
  #- search.share     # Adds an option to share a search query link.*
  #- search.suggest   # Search will suggest the likeliest completion for a word.*
  
  # Table of Contents
  #
  # - toc.integrate          # Include the TOC sections in the left navugation.
  - toc.follow
  icon:
    logo: 'material/library'
    repo: 'material/library'
  #admonition:
  #    note: 'octicons/tag-16'
  #    abstract: 'octicons/checklist-16'
  #    info: 'octicons/info-16'
  #    tip: 'octicons/squirrel-16'
  #    success: 'octicons/check-16'
  #    question: 'octicons/question-16'
  #    warning: 'octicons/alert-16'
  #    failure: 'octicons/x-circle-16'
  #    danger: 'octicons/zap-16'
  #    bug: 'octicons/bug-16'
  #    example: 'octicons/beaker-16'
  #    quote: 'octicons/quote-16'
extra_css:
- stylesheets/extra.css
extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://jkk-research/jkk-research.github.io'
markdown_extensions:
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - md_in_html
  - markdown.extensions.admonition:
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: true
  #- pymdownx.arithmex:
  #- pymdownx.b64:
  #- pymdownx.betterem:
  #- pymdownx.caret:
  #- pymdownx.critic:
  #- pymdownx.details:
  #- pymdownx.emoji:
  #- pymdownx.escapeall:
  #- pymdownx.extra:
  #- pymdownx.extrarawhtml:
  #- pymdownx.highlight:
  #- pymdownx.inlinehilite:
  #- pymdownx.keys:
  #- pymdownx.magiclink:
  #- pymdownx.mark:
  #- pymdownx.pathconverter:
  #- pymdownx.progressbar:
  #- pymdownx.smartsymbols:
  #- pymdownx.snippets:
  #- pymdownx.striphtml:
  #- pymdownx.superfences:
  #- pymdownx.tabbed:
  #- pymdownx.tasklist:
  #- pymdownx.tilde:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # - pymdownx.highlight:
  #   anchor_linenums: true
  #   line_spans: __span
  #   pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true

# plugins:
#   - meta